#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9
ENV_FILE=".acceptance-run.env"

# Self-locating, like this repo's other scripts (scripts/sync-runtime.mjs): never hardcode
# where the repo lives, so this still works from a fresh clone anywhere.
UAS_REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SETUP_CLI="$UAS_REPO/skills/engineering/setup-universal-agent-skills/scripts/universal-agent-skills.mjs"
# ADR 0004 designates the repo's own parent directory (C:\Handoff on this machine) as the
# dedicated exercise workspace; override with FIXTURE_ROOT=... if yours differs.
FIXTURE_ROOT="${FIXTURE_ROOT:-$(dirname "$UAS_REPO")}"
CODEX_FIXTURE="$FIXTURE_ROOT/acceptance-codex"
CLAUDE_FIXTURE="$FIXTURE_ROOT/acceptance-claude"
CLAUDE_PLUGIN_FIXTURE="$FIXTURE_ROOT/acceptance-claude-plugin"
CODEX_WORK_ITEM="codex-accept-1"
CLAUDE_WORK_ITEM="claude-accept-1"
CLAUDE_PLUGIN_WORK_ITEM="claude-plugin-accept-1"
ACCEPT_WINDOW=40000   # deliberately small: the reserve clamp installs a ~10k-token compact threshold, so 3 real
                       # compactions are reachable without six-figure token spend (#11/#12
                       # "cost-conscious acceptance profile").

_init_fixture() {
  local dir="$1"
  if [[ -d "$dir/.git" ]]; then
    note "$dir already exists; reusing it."
    return
  fi
  mkdir -p "$dir"
  git -C "$dir" init -q -b main
  git -C "$dir" config user.email "acceptance@example.invalid"
  git -C "$dir" config user.name "Acceptance fixture"
  printf 'Disposable native-acceptance fixture. Never pushed anywhere.\n' > "$dir/README.md"
  git -C "$dir" add README.md
  git -C "$dir" commit -q -m "fixture"
  printf '  %s✓%s created %s\n' "$GREEN" "$RESET" "$dir"
}

_installed_cli() { printf '%s/.agents/universal-agent-skills/runtime/cli.mjs' "$1"; }

banner "Native compaction acceptance run (#11, #12)"
say "This sets up three disposable fixtures and binds each to a real host session."
say "It does NOT run the compaction work itself — that's real, live, open-ended usage"
say "no script can walk you through. Stage 9 hands you that runbook directly."
warn "Every fixture lives under $FIXTURE_ROOT, is git-local only, and is never pushed."
warn "This never touches C:\\SkillTest, tdg-movingforward/company-platform, or any other project."

# ── Stage 1: create the three disposable fixtures ──────────────────────────
stage "Create the disposable fixtures"
say "Three fixtures, one per acceptance track:"
note "  $CODEX_FIXTURE          — Codex, direct Universal adapter (full run + experiments)"
note "  $CLAUDE_FIXTURE         — Claude, direct Universal adapter (full run + experiments)"
note "  $CLAUDE_PLUGIN_FIXTURE  — Claude, plugin-delegated only (proves real delegation)"
if confirm "Create/verify these three git-local fixture directories now?"; then
  _init_fixture "$CODEX_FIXTURE"
  _init_fixture "$CLAUDE_FIXTURE"
  _init_fixture "$CLAUDE_PLUGIN_FIXTURE"
else
  warn "Skipped. Re-run this wizard when you're ready; it's idempotent."
fi

# ── Stage 2: Codex fixture — cost-conscious runtime setup ──────────────────
stage "Codex fixture: install the continuity runtime"
say "Installing the Codex adapter with a small context window, so the compact"
say "threshold lands around 10k tokens (the 30k reserve clamps it) instead of requiring a huge real session."
step "Running setup non-interactively against $CODEX_FIXTURE ..."
node "$SETUP_CLI" setup --hosts codex --context-window "$ACCEPT_WINDOW" --project "$CODEX_FIXTURE"
note "Check the JSON above: adapters[0].threshold.compactTokens is the real trigger point."
pause "Reviewed the output? Press Enter to continue."

# ── Stage 3: Codex fixture — hook trust ─────────────────────────────────────
stage "Codex fixture: trust the project hooks"
say "Codex only runs project-local hooks after you explicitly trust them — this"
say "step genuinely cannot be scripted; it's an interactive TUI approval."
step "In a terminal: cd \"$CODEX_FIXTURE\" && codex"
step "If Codex doesn't prompt automatically, run the /hooks command inside that"
step "session and trust the managed PreCompact/PostCompact/SessionStart entries."
warn "Leave this Codex session running — the next stage binds it while it's still open."
pause "Hooks trusted, and the Codex session is still open? Press Enter to continue."

# ── Stage 4: Codex fixture — discover and bind the live session ────────────
stage "Codex fixture: bind the live session to a Work Item ID"
say "Codex has no flag to pre-choose a new session's ID, so we discover it from"
say "the rollout file it just started writing (confirmed against this machine's"
say "own ~/.codex/sessions/ layout: rollout-<timestamp>-<uuid>.jsonl, one UUID"
say "per session). In a SECOND terminal, with that Codex session still open:"
step "ls -t ~/.codex/sessions/\$(date +%Y/%m/%d)/*.jsonl | head -1"
note "The UUID at the end of that filename (before .jsonl) is the session ID."
note "Sanity check: its mtime should be from just now, not an older session."
ask CODEX_SESSION_ID "Paste the discovered Codex session UUID:"
write_env CODEX_SESSION_ID "$CODEX_SESSION_ID"
step "Binding it to work item $CODEX_WORK_ITEM ..."
node "$(_installed_cli "$CODEX_FIXTURE")" activate \
  --work-item "$CODEX_WORK_ITEM" --harness codex --session "$CODEX_SESSION_ID" \
  --project "$CODEX_FIXTURE"
write_env CODEX_WORK_ITEM "$CODEX_WORK_ITEM"

# ── Stage 5: Claude (direct) fixture — cost-conscious runtime setup ────────
stage "Claude fixture (direct adapter): install the continuity runtime"
say "Same small window, direct Universal adapter (no plugin) — this is the track"
say "that runs the full 3x-compaction proof plus the concurrent/stale/fail-open"
say "experiments."
step "Running setup non-interactively against $CLAUDE_FIXTURE ..."
node "$SETUP_CLI" setup --hosts claude --context-window "$ACCEPT_WINDOW" --project "$CLAUDE_FIXTURE"
note "Check adapters[0].threshold.compactTokens in the output above."
pause "Reviewed the output? Press Enter to continue."

# ── Stage 6: Claude (direct) fixture — pre-chosen session id, bind, start ──
stage "Claude fixture (direct adapter): bind and start the live session"
say "Unlike Codex, Claude Code lets us pre-choose the session ID with"
say "--session-id, so there's no discovery step — bind first, then start."
if [[ -z "$(_existing CLAUDE_SESSION_ID || true)" ]]; then
  if command -v uuidgen >/dev/null 2>&1; then write_env CLAUDE_SESSION_ID "$(uuidgen)"
  else write_env CLAUDE_SESSION_ID "$(node -e "console.log(require('node:crypto').randomUUID())")"; fi
fi
ask CLAUDE_SESSION_ID "Use this Claude session UUID (Enter to accept, or paste your own):"
write_env CLAUDE_SESSION_ID "$CLAUDE_SESSION_ID"
step "Binding it to work item $CLAUDE_WORK_ITEM ..."
node "$(_installed_cli "$CLAUDE_FIXTURE")" activate \
  --work-item "$CLAUDE_WORK_ITEM" --harness claude --session "$CLAUDE_SESSION_ID" \
  --project "$CLAUDE_FIXTURE"
write_env CLAUDE_WORK_ITEM "$CLAUDE_WORK_ITEM"
say "Now, in a terminal:"
step "cd \"$CLAUDE_FIXTURE\" && claude --session-id \"$CLAUDE_SESSION_ID\""
step "Once inside, run /autocompact and note the effective capacity and trigger —"
step "that's required evidence for #12."
pause "Session started with that exact --session-id? Press Enter to continue."

# ── Stage 7: Claude plugin fixture — install and verify ────────────────────
stage "Claude plugin fixture: install session-durability"
say "This proves genuine plugin delegation (#9's acceptance), not the no-op path"
say "you'd get if a direct adapter were also present — so this fixture gets ONLY"
say "the plugin, never 'setup --hosts claude'."
step "Inside any Claude Code session (installs at the user level, not per-project):"
step "  /plugin marketplace add kaizen2026/claude-agent-skills"
step "  /plugin install session-durability@claude-skills"
pause "Plugin installed? Press Enter to continue."
say "Now bootstrap just the continuity runtime files into the plugin fixture"
say "(no adapter, no hooks — those come from the plugin, not this):"
node "$SETUP_CLI" setup --hosts none --context-window "$ACCEPT_WINDOW" --project "$CLAUDE_PLUGIN_FIXTURE"

# ── Stage 8: Claude plugin fixture — bind and start ─────────────────────────
stage "Claude plugin fixture: bind and start the live session"
if [[ -z "$(_existing CLAUDE_PLUGIN_SESSION_ID || true)" ]]; then
  if command -v uuidgen >/dev/null 2>&1; then write_env CLAUDE_PLUGIN_SESSION_ID "$(uuidgen)"
  else write_env CLAUDE_PLUGIN_SESSION_ID "$(node -e "console.log(require('node:crypto').randomUUID())")"; fi
fi
ask CLAUDE_PLUGIN_SESSION_ID "Use this Claude session UUID (Enter to accept, or paste your own):"
write_env CLAUDE_PLUGIN_SESSION_ID "$CLAUDE_PLUGIN_SESSION_ID"
node "$(_installed_cli "$CLAUDE_PLUGIN_FIXTURE")" activate \
  --work-item "$CLAUDE_PLUGIN_WORK_ITEM" --harness claude --session "$CLAUDE_PLUGIN_SESSION_ID" \
  --project "$CLAUDE_PLUGIN_FIXTURE"
write_env CLAUDE_PLUGIN_WORK_ITEM "$CLAUDE_PLUGIN_WORK_ITEM"
say "In a terminal:"
step "cd \"$CLAUDE_PLUGIN_FIXTURE\" && claude --session-id \"$CLAUDE_PLUGIN_SESSION_ID\""
say "Work normally through one real PreCompact/SessionStart(compact) cycle — you"
say "don't need all 3 here, just enough to see the plugin actually deliver."
say "Afterward, confirm delegation was real, not silent:"
step "ls \"$CLAUDE_PLUGIN_FIXTURE/.agents/state/continuity/work-items/$CLAUDE_PLUGIN_WORK_ITEM/events.jsonl\""
note "That file existing with an entry means delegate.mjs really ran the runtime."
pause "Confirmed the plugin delegated for real? Press Enter to continue."
say "Optional, cheap proof of #9's 'exactly one registration mode' guarantee —"
say "layer the direct adapter on top of the same fixture and confirm it no-ops:"
step "node \"$SETUP_CLI\" setup --hosts claude --context-window $ACCEPT_WINDOW --project \"$CLAUDE_PLUGIN_FIXTURE\""
step "Then fire one more PreCompact for real and confirm only ONE new event line"
step "appears in events.jsonl, not two."
note "This is already covered by an automated test in claude-agent-skills; treat"
note "this as a live sanity check, not the primary proof. Skip it if you'd rather not."

# ── Stage 9: the live-work runbook (not scriptable — read and follow) ──────
stage "The live-work runbook (#11 / #12) — read this, then go work"
say "Everything below happens in the live sessions you just started. This isn't"
say "a script because it's real, open-ended usage — do it, then come back."
say ""
say "─ For EACH of the Codex fixture and the Claude (direct) fixture ─"
step "1. Work normally on something real in that session (code, docs, anything) until"
step "   native compaction fires. Repeat until it has fired 3 times in the SAME"
step "   continuing session — don't restart the session between boundaries."
step "2. After boundary 1, from a second terminal, prove concurrent contribution:"
note "   node \"<fixture>/.agents/universal-agent-skills/runtime/cli.mjs\" checkpoint \\"
note "     --work-item <work-item> --harness <codex|claude> --session <session-id> \\"
note "     --expected-revision <the revision status just reported> \\"
note "     --decisions \"Concurrent collaborator note.\" --project <fixture>"
note "   Run it once with the correct current revision (must succeed). Immediately"
note "   run it again with that SAME now-stale revision (must report reason:"
note "   stale-revision and write a proposal under work-items/<id>/proposals/)."
step "3. Between boundaries 2 and 3, inject a failure and confirm fail-open:"
note "   mv <fixture>/.agents/state/continuity/work-items/<id>/events.jsonl{,.bak}"
note "   mkdir <fixture>/.agents/state/continuity/work-items/<id>/events.jsonl"
note "   # fire one hook by hand with a synthetic payload (codex needs turn_id +"
note "   # a manual|auto trigger; claude does not require either):"
note "   echo '{\"session_id\":\"<session-id>\",\"turn_id\":\"manual-fail-open\",\"trigger\":\"manual\"}' | \\"
note "     node <fixture>/.agents/universal-agent-skills/runtime/cli.mjs hook <codex|claude> PreCompact --project <fixture>"
note "   Confirm the reply is a degraded systemMessage and diagnostics.jsonl grew"
note "   by one entry — then restore:"
note "   rmdir <fixture>/.agents/state/continuity/work-items/<id>/events.jsonl"
note "   mv <fixture>/.agents/state/continuity/work-items/<id>/events.jsonl{.bak,}"
step "4. For the Claude fixture only: capture /autocompact output again at the end"
step "   (effective capacity, override percentage) — #12 wants both."
say ""
say "─ Evidence to keep for both tracks (I'll gather these myself afterward) ─"
note "  - Each fixture's events.jsonl, diagnostics.jsonl, and every work item's"
note "    semantic.md + proposals/ directory."
note "  - The three SessionStart(compact) injected-context payloads (paste from"
note "    the terminal, or note the model/timestamp if not captured live)."
note "  - git log inside each fixture (proves nothing was pushed anywhere)."
warn "No test secrets: don't paste real credentials into these sessions."
say ""
say "When all three tracks are done, tell me — I'll pull the evidence files"
say "myself and write up #11 and #12."

finish
say "Fixture paths and captured IDs are saved in $ENV_FILE for re-runs."
